### ISSUE TITLE
"std::invalid_argument" being thrown when trying to send audio

### ISSUE THREAD

**Issue by KeithsCreations** [CS179J-Team08/CS179J-Team08-Project#35]
In the KeithsCreations/more_effects branch, there is currently a bug that crashes the cloud_sound binary when loading a song. More specifically, this happens as the parameters for the "pitchshift" effect are being loaded. The following error appears:

```
terminate called after throwing an instance of 'std::invalid_argument'
what(): stof
Aborted
```

**Comment by Arent128** [comment]
This issue is depreciated. Look towards #36 for an update on the matter.
