### ISSUE TITLE
'std::logic_error' thrown after Data parsing

### ISSUE THREAD

**Issue by KeithsCreations** [CS179J-Team08/CS179J-Team08-Project#36]
The cloud_sound binary will throw an instance of 'std::logic_error' after the data gets parsed. It will list the values of all the parameters up to equalizer before reaching `Data parsed`.

Full error:
```
terminate called after throwing an instance of 'std::logic_error'
 what(): basic_string::_M_construct null not valid
Aborted
```

**Comment by KeithsCreations** [comment]
![image](https://user-images.githubusercontent.com/27966942/83397429-77584080-a3b2-11ea-8b1a-c92f16d9d87d.png)

**Comment by Arent128** [comment]
The reason you are getting that error is that packet has a URL containing the audio to play, but the PacketParser you currently have is out of date. It will not parse the URL and as a result, that error occurs. I updated the branch on my local machine though I still get errors as shown below.
![effects_bug](https://user-images.githubusercontent.com/43712723/83403542-c9eb2a00-a3bd-11ea-85b1-85c6cabb4d27.png)

**Comment by Arent128** [comment]
At the moment it seems that the pitchshift effect is the main offender in causing the above segmentation fault. It segfaults when it goes to add the DSP effect to the system with the offending line being 438 in the image below.
![AudioEngine_pitchshift_bug](https://user-images.githubusercontent.com/43712723/83405509-7b3f8f00-a3c1-11ea-9190-aba6936cccc0.png)
